###########################################################################
### Application 설정
###########################################################################
application:

  frontend:
    scheme: http
    host: admin.hooni.co.kr
    port: 80
  gateway: http://admin-gateway.hooni.co.kr

  cors:
    allowed-origin:
    - http://admin.hooni.co.kr

###########################################################################
### server 설정
###########################################################################
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: lax
  error:
    whitelabel:
      enabled: false